name: BuildTest
on:
  push:
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: 11
          distribution: corretto
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4.2
      - name: Gradle build
        run: gradle build
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: build
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: build
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: corretto
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4.2
      - name: Unit test
        run: gradle test
  deploy:
    name: Publish
    runs-on: ubuntu-latest
    needs: test
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: artifacts
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: corretto
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4.2
      - name: Publish libraries
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: gradle publish --no-daemon